github:
  client:
    clientId: b1167ad8a140565fd637
    clientSecret: 875cf2cd2ce99161f552e99816b2db84fd2dcf07
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: gist,repo
#    auto-aprove-scopes: '.*'
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG
